repositories:
  remote:
   - https://repo.maven.apache.org/maven2
   - https://repository.jboss.org/

artifacts:
  javax_annotation: org.realityforge.javax.annotation:javax.annotation:jar:1.0.0

  getopt4j: org.realityforge.getopt4j:getopt4j:jar:0.3

  javax_json: org.glassfish:javax.json:jar:1.1

  revapi: org.revapi:revapi:jar:0.10.2
  revapi_basic_features: org.revapi:revapi-basic-features:jar:0.7.4
  revapi_java_spi: org.revapi:revapi-java-spi:jar:0.17.2
  revapi_java: org.revapi:revapi-java:jar:0.18.2
  dmr: org.jboss:jboss-dmr:jar:1.2.0.Final
  cookcc: com.google.code.cookcc:cookcc:jar:0.3.3
  slf4j_api: org.slf4j:slf4j-api:jar:1.7.5
  slf4j_jdk14: org.slf4j:slf4j-jdk14:jar:1.7.5
